services:
  - type: web
    name: google-drive-tgs3
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TGS3_PASSWORD
        sync: false
      - key: DATABASE_PATH
        value: "/app/.data/files.db"
      - key: TELEGRAM_SESSION
        value: "/app/.data/telegram.session"

